[user]
name = "Toby DiPasquale"
email = "toby.dipasquale@vanta.com"

[ui]
default-command = "log"
diff-formatter = ":git"
editor = "vim"

[templates]
git_push_bookmark = '"toby-vanta/push-" ++ change_id.short()'

[aliases]
l = ["log", "-r", "::@"]
lm = ["log", "-r", "(main..@):: | (main..@)-"]
la = ["log", "-r", "::"]
rba = ["rebase", "-b", "all:open", "-d", "main"]

[revset-aliases]
open = 'bookmarks(regex:"^toby-vanta/push-*")'

