[user]
name = "Toby DiPasquale"
email = "toby.dipasquale@vanta.com"

[ui]
default-command = "log"
editor = "vim"

[aliases]
l = ["log", "-r", "::@"]
lm = ["log", "-r", "(main..@):: | (main..@)-"]
la = ["log", "-r", "::"]
