[user]
name = "Toby DiPasquale"
email = "toby.dipasquale@vanta.com"

[ui]
default-command = "log"
diff-formatter = ":git"
editor = "vim"

[git]
push-bookmark-prefix = "toby-vanta/push-"

[aliases]
l = ["log", "-r", "::@"]
lm = ["log", "-r", "(main..@):: | (main..@)-"]
la = ["log", "-r", "::"]
